export enum EventTypes {
  UpdatePower = 'update-power',
  UpdateAlert = 'update-alert',
  UpdateTemperature = 'update-temperature',
  UpdateHumidity = 'update-humidity',
  UpdateCo2 = 'update-co2',
  UpdateThermostatTemp = 'update-thermostat_temp',

  MqttMessage = 'mqtt-message',

  NewStats = 'stats->new',
  NewStatsEx = 'stats->new-ex',

  WiFiConnect = 'wifi->connect',
  WiFiConnected = 'wifi->connected',
  WiFiNetworkFound = 'wifi->network-found',

  SettingsReady = 'settings->ready',
  ApplicationReady = 'application->ready',
  ApplicationCreated = 'application->created',
  ApplicationGetDevices = 'application->getDevices',
  ApplicationGetZoneDevices = 'application->getZoneDevices',
  ApplicationGetConfig = 'application->getConfig',
  ApplicationUpdateConfig = 'application->updateConfig',
  ApplicationDeviceCommand = 'application->deviceCommand',
  ApplicationDeviceCustomData = 'application->getDeviceCustomData',
  ApplicationGetTable = 'application->getTable',
  ApplicationCreateTable = 'application->createTable',
  ApplicationUpdateTable = 'application->updateTable',
  ApplicationDeviceEvent = 'application->deviceEvent',
  ApplicationGetDisplay = 'application->getDisplay',
  ApplicationAddDeviceQueue = 'application->addDeviceQueue',
  ApplicationAddScanQueue = 'application->addScanQueue',
  NewEvent = 'application->new-event',
  ApplicationDriverReady = 'application->driverReady',
  ApplicationMemUsage = 'application->memUsage',
  ApplicationWsReceive = 'application->wsReceive',
  ApplicationWsEmit = 'application->wsEmit',
  ApplicationWsEmitEx = 'application->wsEmitEx',
  ApplicationSendNotification = 'application->sendNotification',
  ApplicationDeviceRestart = 'application->deviceRestart',
  ApplicationUpdatePlugins = 'application->updatePlugins',
  ApplicationUpdate = 'application->update',
  ApplicationCloudRegister = 'application->cloudRegister',
  ApplicationCloudBaseRequestEx = 'application->cloudBaseRequestEx',
  ApplicationSubscribeDevice = 'application->subscribeDevice',
  ApplicationUpdateClients = 'application->updateClients',
  ApplicationSavePlugins = 'application->savePlugins',

  DatabaseReady = 'database->ready',
  DatabaseConnected = 'database->connected',
  DatabaseGetAllItems = 'database->getAllItems',
  DatabaseUpdateItem = 'database->updateItem',
  DatabaseUpdateDeviceParams = 'database->updateDeviceParams',
  DatabaseCreateItem = 'database->createItem',
  DatabaseQuery = 'database->query',
  DatabaseUpdate = 'database->update',
  DatabaseQueueQuery = 'database->queueQuery',
  DatabaseRestore = 'database->restore',
  DatabaseBackup = 'database->backup',

  CheckSubDevice = 'check-sub-device',
  Publish = 'publish',
  Notify = 'notify',
  NotifyEx = 'notify-ex',
  Exception = 'exception',
  SendNotification = 'send-notification',

  DeviceCreate = 'device->create',
  DeviceUpdate = 'device->update',
  DeviceDone = 'device->done',
  DeviceConnect = 'device->connect',
  DeviceDelete = 'device->delete',
  DeviceDiscover = 'device->discover',
  DeviceCheckSubDevice = 'device->check-sub-device',

  DevicesInit = 'devices->init',
  DevicesFind = 'devices->find',
  DevicesGet = 'devices->get',
  DevicesList = 'devices->list',
  DevicesAdd = 'devices->add',

  UpdateSensor = 'sensor->update',
  RemoveSensor = 'sensor->remove',
  UpdateSensorEx = 'sensor->update-ex',

  ChangedMotion = 'changed_motion',
  ChangedMagnet = 'changed_magnet',
  ChangedMagnetChange = 'changed_magnet_change',
  ChangedPower = 'changed_power',
  ChangedPowerChange = 'changed_power_change',
  ChangedAction = 'changed_action',
  ChangedLeakChange = 'changed_leak_change',
  ChangedInputChange = 'changed_input_change',
  ChangedCounterChange = 'changed_counter_change',
  ChangedPowerLoad = 'changed_power_load',
  ChangedChannel0 = 'changed_channel_0',
  ChangedChannel1 = 'changed_channel_1',
  ChangedChannel = 'changed_channel',
  ChangedDoorbell = 'changed_doorbell',
  ChangedVoltage = 'changed_voltage',
  ChangedTemperature = 'changed_temperature',
  ChangedTargetTemperature = 'changed_target_temperature',
  ChangedTargetCo2 = 'changed_target_co2',
}